version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ImgApi
      - POSTGRES_USER=jxbllsdy
      - POSTGRES_PASSWORD=NtCTt11Eaxsw_FooI8n7iX7WPTMPgH
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=jxbllsdy
      - POSTGRES_USER=jxbllsdy
      - POSTGRES_PASSWORD=NtCTt11Eaxsw_FooI8n7iX7WPTMPgH
    depends_on:
      - db

