# Generated by Django 4.0.4 on 2022-06-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(editable=False, upload_to='tumbs/'),
        ),
    ]
