# Generated by Django 4.0.4 on 2022-05-29 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_alter_image_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['date_added']},
        ),
    ]
